### ISSUE TITLE
Command to find user timezone

### ISSUE THREAD

**Issue by tbille** [canonical-web-and-design/webteam-hubot#106]
`/tz @user` could give me the timezone and the working hours of a user

**Comment by sowasred2012** [comment]
Looks like [this was added](https://github.com/canonical-web-and-design/webteam-hubot/commit/bfd2e5bee14f7eb7af08a5ff50a6c23716457f9b#diff-046d21bcf3b9eab47a3052e0cf5b01a2fb98dea91cd4faa6f1e1979915f5509e) (but later [removed](https://github.com/canonical-web-and-design/webteam-hubot/pull/129) 😭)
