### ISSUE TITLE
IRC bot: Pick a random developer

### ISSUE THREAD

**Issue by nottrobin** [canonical-web-and-design/webteam-hubot#29]
Update the IRC bot to randomly choose a developer when it sends a message about a PR.

I think for the time being we should do this as light-weight as possible - which is probably simply to add a list of all developer IRC nicknames to the IRC bot codebase, and just randomly pick one when sending a PR message.

Down the line this could be improved by (but these should be out of scope for the time being - or stretch tasks):

- Getting the list of developers from a team in GitHub through the GitHub API
- Inspecting GitHub to pick developers who don't have many PRs assigned to them already
- Maybe pick developers based on those not so experienced with a project or something?

**Comment by tbille** [comment]
Maybe then not part of the webbot project.
Closing the issue.
